# The Docker image that will be used to build your app
image: "npm: 8.19.2"
# Functions that should be executed before the build script is run
before_script:
  - npm ci
pages:
  script:
    - npm install
    - npm test
    - npx eslint js/*.js
  artifacts:
    paths:
      # The folder that contains the files to be exposed at the Page URL
      - .
  rules:
    # This ensures that only pushes to the default branch will trigger
    # a pages deploy
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH