concurrent = 1
check_interval = 0
shutdown_timeout = 0

[session_server]
  session_timeout = 1800

[[runners]]
  name = "runner_mapCamping"
  url = "https://gitlab.com"
  id = 25687120
  token = "glrt-4CRwozswvngpiFW7FqfG"
  token_obtained_at = 2023-08-02T20:09:37Z
  token_expires_at = 0001-01-01T00:00:00Z
  executor = "shell"
  shell = "pwsh"

[[runners]]
  name = "map_camping"
  url = "https://gitlab.com"
  id = 25688840
  token = "glrt-pir87teQUaxhtauTyQQE"
  token_obtained_at = 2023-08-02T21:53:43Z
  token_expires_at = 0001-01-01T00:00:00Z
  executor = "shell"
  shell = "pwsh"
  [runners.cache]
    MaxUploadedArchiveSize = 0
