concurrent = 1
check_interval = 0
shutdown_timeout = 0

[session_server]
  session_timeout = 1800

[[runners]]
  name = "map_camping"
  url = "https://gitlab.com"
  id = 25689088
  token = "glrt-h7nyH_S2kWALUykqBaFs"
  token_obtained_at = 2023-08-02T22:21:46Z
  token_expires_at = 0001-01-01T00:00:00Z
  executor = "shell"
  shell = "pwsh"
  [runners.cache]
    MaxUploadedArchiveSize = 0
